import { useEffect, useState, type FormEvent } from 'react'
type Props={path:string;csrfToken:string;onNavigate:(path:string)=>void}
type Ticket={id:number;ticketNumber:string;summary:string;currentStatus:string;requestedPriority:string;lastUpdated:string}
type Attachment={id:number;displayName:string;removedAt:string|null;removalReason:string|null;isActive:boolean;downloadUrl:string|null}
type Detail=Ticket&{description:string;problemAppearsResolved:boolean;version:number;attachments:Attachment[];comments?:Array<{id:number;body:string;createdAt:string;author:{name:string}} >}
type Ref={id:number;name:string}
export default function RequesterWorkspace({path,csrfToken,onNavigate}:Props){
 const [tickets,setTickets]=useState<Ticket[]>([]),[detail,setDetail]=useState<Detail|null>(null),[comments,setComments]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[cats,setCats]=useState<Ref[]>([]),[systems,setSystems]=useState<Ref[]>([]),[form,setForm]=useState({categoryId:'',relatedSystemId:'',requestedPriority:'LOW',summary:'',description:''}),[file,setFile]=useState<File|null>(null),[reason,setReason]=useState('')
 const load=async()=>{const r=await fetch('/api/tickets');if(!r.ok)throw Error('Tickets could not be loaded.');setTickets((await r.json()).items)}
 useEffect(()=>{if(path==='/tickets')void load().catch(e=>setError(e.message));if(path==='/tickets/new')void Promise.all([fetch('/api/categories'),fetch('/api/related-systems')]).then(async([a,b])=>{if(a.ok&&b.ok){setCats(await a.json());setSystems(await b.json())}})},[path])
 const open=async(id:number)=>{const r=await fetch(`/api/tickets/${id}`);if(!r.ok){setError('Ticket could not be loaded.');return}const d=await r.json();const c=await fetch(`/api/tickets/${id}/comments`);d.comments=(await c.json()).items;setDetail(d);onNavigate(`/tickets/${id}`)}
 const post=async()=>{if(!detail||!comments.trim())return;setBusy(true);try{const r=await fetch(`/api/tickets/${detail.id}/comments`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({body:comments})});const p=await r.json();if(!r.ok)throw Error(p.error?.message??'Comment could not be posted.');setDetail({...detail,comments:[...(detail.comments??[]),p]});setComments('')}catch(e){setError(e instanceof Error?e.message:'Comment could not be posted.')}finally{setBusy(false)}}
 const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await fetch('/api/tickets',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({...form,categoryId:Number(form.categoryId),relatedSystemId:Number(form.relatedSystemId),clientRequestId:crypto.randomUUID()})});const d=await r.json();if(!r.ok)throw Error(d.error?.message??'Ticket could not be created.');if(file){const fd=new FormData();fd.append('file',file);await fetch(`/api/tickets/${d.id}/attachments`,{method:'POST',headers:{'X-CSRF-Token':csrfToken},body:fd})}await open(d.id)}catch(e){setError(e instanceof Error?e.message:'Ticket could not be created.')}finally{setBusy(false)}}
 const indicator=async()=>{if(!detail)return;const r=await fetch(`/api/tickets/${detail.id}/resolution-indicator`,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({problemAppearsResolved:!detail.problemAppearsResolved,version:detail.version})});const d=await r.json();if(!r.ok){setError(d.error?.message??'Indicator could not be updated.');return}setDetail({...detail,...d})}
 const remove=async(id:number)=>{if(!detail||reason.trim().length<3)return;const r=await fetch(`/api/tickets/${detail.id}/attachments/${id}`,{method:'DELETE',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({removalReason:reason.trim()})});if(!r.ok){setError('Attachment could not be removed.');return}setReason('');await open(detail.id)}
 if(path==='/tickets/new')return <section><button onClick={()=>onNavigate('/tickets')}>Back to My Tickets</button><h1>Create Ticket</h1>{error&&<p role="alert">{error}</p>}<form onSubmit={create}><label>Category<select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Select category</option>{cats.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Related System<select required value={form.relatedSystemId} onChange={e=>setForm({...form,relatedSystemId:e.target.value})}><option value="">Select system</option>{systems.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Requested Priority<select value={form.requestedPriority} onChange={e=>setForm({...form,requestedPriority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label>Summary<input required minLength={5} maxLength={120} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label>Description<textarea required minLength={20} maxLength={4000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Attachment<input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button disabled={busy}>Create Ticket</button></form></section>
 if(path==='/tickets')return <section><h1>My Tickets</h1><button onClick={()=>onNavigate('/tickets/new')}>Create Ticket</button>{error&&<p role="alert">{error}</p>}{tickets.length===0?<p>No tickets yet.</p>:<ul>{tickets.map(t=><li key={t.id}><button onClick={()=>void open(t.id)}>{t.ticketNumber}</button> — {t.summary} ({t.currentStatus})</li>)}</ul>}</section>
 if(detail)return <section><button onClick={()=>{setDetail(null);onNavigate('/tickets')}}>Back to My Tickets</button><h1>{detail.ticketNumber}</h1><p>{detail.description}</p><p>Status: {detail.currentStatus} · Requested Priority: {detail.requestedPriority}</p><button disabled={busy} onClick={()=>void indicator()}>{detail.problemAppearsResolved?'Clear':'Mark'} Problem Appears Resolved</button><h2>Attachments</h2>{detail.attachments.map(a=><div key={a.id}><span>{a.displayName}</span>{a.isActive?<><a href={a.downloadUrl??'#'}>Download</a><input aria-label="Removal reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Removal reason"/><button onClick={()=>void remove(a.id)}>Remove</button></>:<span>Removed: {a.removalReason}</span>}</div>)}<h2>Public Comments</h2>{(detail.comments??[]).map(c=><article key={c.id}><strong>{c.author.name}</strong><time> {c.createdAt}</time><p>{c.body}</p></article>)}<label>Comment<textarea value={comments} maxLength={2000} onChange={e=>setComments(e.target.value)}/></label><button disabled={busy||!comments.trim()} onClick={()=>void post()}>Post public comment</button>{error&&<p role="alert">{error}</p>}</section>
 return <section><h1>Access unavailable</h1><button onClick={()=>onNavigate('/tickets')}>Return to My Tickets</button></section>
}
