import { useEffect, useState } from 'react'
type Props={path:string;csrfToken:string;onNavigate:(p:string)=>void};type Ticket={id:number;ticketNumber:string;summary:string;currentStatus:string;requestedPriority:string;itPriority:string;version:number;assignedTo?:{id:number;name:string;role:string}|null;description?:string;attachments?:any[]}
const statuses=['NEW','OPEN','IN_PROGRESS','WAITING_FOR_REQUESTER','RESOLVED','CLOSED','REOPENED','CANCELLED']
export default function StaffWorkspace({path,csrfToken,onNavigate}:Props){const[items,setItems]=useState<Ticket[]>([]),[detail,setDetail]=useState<Ticket|null>(null),[assignees,setAssignees]=useState<any[]>([]),[comments,setComments]=useState<any[]>([]),[notes,setNotes]=useState<any[]>([]),[draft,setDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{const r=await fetch('/api/staff/tickets');if(!r.ok)throw Error('Queue unavailable.');setItems((await r.json()).items)};useEffect(()=>{if(path==='/staff/tickets')void load().catch(e=>setError(e.message))},[path])
 const open=async(id:number)=>{const[t,c,n,a]=await Promise.all([fetch(`/api/tickets/${id}`),fetch(`/api/tickets/${id}/comments`),fetch(`/api/tickets/${id}/internal-notes`),fetch('/api/staff/assignees')]);if(!t.ok){setError('Ticket detail unavailable.');return}setDetail(await t.json());setComments((await c.json()).items);setNotes((await n.json()).items);setAssignees((await a.json()).items);onNavigate(`/staff/tickets/${id}`)}
 const mutate=async(url:string,body:unknown)=>{if(!detail)return;setBusy(true);try{const r=await fetch(url,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error?.message??'Update failed.');setDetail(d);await load()}catch(e){setError(e instanceof Error?e.message:'Update failed.')}finally{setBusy(false)}}
 const post=async(kind:'comments'|'internal-notes')=>{if(!detail||!draft.trim())return;const r=await fetch(`/api/tickets/${detail.id}/${kind}`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({body:draft})});const d=await r.json();if(!r.ok){setError(d.error?.message??'Post failed.');return}kind==='comments'?setComments([...comments,d]):setNotes([...notes,d]);setDraft('')}
 if(path==='/staff/tickets')return <section><h1>Ticket Queue</h1>{error&&<p role="alert">{error}</p>}{items.length===0?<p>No tickets found.</p>:<table><thead><tr><th>Ticket</th><th>Summary</th><th>Requested Priority</th><th>IT Priority</th><th>Status</th><th>Owner</th><th>Action</th></tr></thead><tbody>{items.map(t=><tr key={t.id}><td>{t.ticketNumber}</td><td>{t.summary}</td><td>{t.requestedPriority}</td><td>{t.itPriority}</td><td>{t.currentStatus}</td><td>{t.assignedTo?.name??'Unassigned'}</td><td><button onClick={()=>void open(t.id)}>Open</button></td></tr>)}</tbody></table>}</section>
 if(detail)return <section><button onClick={()=>{setDetail(null);onNavigate('/staff/tickets')}}>Back to Queue</button><h1>{detail.ticketNumber}</h1><p>{detail.description}</p>{error&&<p role="alert">{error}</p>}<fieldset><legend>Ownership and workflow</legend><button disabled={busy} onClick={()=>void mutate(`/api/tickets/${detail.id}/assignment`,{action:'claim',version:detail.version})}>Claim</button><label>Assign<select value={detail.assignedTo?.id??''} onChange={e=>void mutate(`/api/tickets/${detail.id}/assignment`,{action:'assign',assignedToId:Number(e.target.value),version:detail.version})}><option value="">Select owner</option>{assignees.map(a=><option key={a.id} value={a.id}>{a.name} ({a.role})</option>)}</select></label><label>IT Priority<select value={detail.itPriority} onChange={e=>void mutate(`/api/tickets/${detail.id}/it-priority`,{itPriority:e.target.value,version:detail.version})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label>Status<select value={detail.currentStatus} onChange={e=>void mutate(`/api/tickets/${detail.id}/status`,{currentStatus:e.target.value,version:detail.version,confirmed:true,reason:'Staff workflow update'})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></fieldset><h2>Attachments</h2>{(detail.attachments??[]).map(a=><div key={a.id}>{a.displayName} {a.downloadUrl&&<a href={a.downloadUrl}>Download</a>}</div>)}<h2>Public Comments</h2>{comments.map(c=><p key={c.id}><strong>{c.author.name}</strong>: {c.body}</p>)}<h2>Internal Notes</h2>{notes.map(n=><p key={n.id}><strong>{n.author.name}</strong>: {n.body}</p>)}<textarea aria-label="New message" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2000}/><button onClick={()=>void post('comments')}>Post public comment</button><button onClick={()=>void post('internal-notes')}>Add internal note</button></section>
 return <section><h1>Access unavailable</h1><button onClick={()=>onNavigate('/staff/tickets')}>Return to Queue</button></section>}
